export const FETCH_SURVEYS_ATTEMPT = 'FETCH_SURVEYS_ATTEMPT';
export const FETCH_SURVEYS_SUCCESS = 'FETCH_SURVEYS_SUCCESS';
export const FETCH_SURVEYS_FAIL = 'FETCH_SURVEYS_FAIL';

export const CREATE_SURVEY_ATTEMPT = 'CREATE_SURVEY_ATTEMPT';
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';
export const CREATE_SURVEY_FAIL = 'CREATE_SURVEY_FAIL';

export const EDIT_SURVEY_ATTEMPT = 'EDIT_SURVEY_ATTEMPT';
export const EDIT_SURVEY_SUCCESS = 'EDIT_SURVEY_SUCCESS';
export const EDIT_SURVEY_FAIL = 'EDIT_SURVEY_FAIL';

export const DELETE_SURVEY_ATTEMPT = 'DELETE_SURVEY_ATTEMPT';
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS';
export const DELETE_SURVEY_FAIL = 'DELETE_SURVEY_FAIL';

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';

export const ADD_CATEGORY_ATTEMPT = 'ADD_CATEGORY_ATTEMPT';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const DELETE_CATEGORY_ATTEMPT = 'DELETE_CATEGORY_ATTEMPT';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAIL = 'DELETE_CATEGORY_FAIL';

export const REDEEM_COUPON_ATTEMPT = 'REDEEM_COUPON_ATTEMPT';
export const REDEEM_COUPON_SUCCESS = 'REDEEM_COUPON_SUCCESS';
export const REDEEM_COUPON_FAIL = 'REDEEM_COUPON_FAIL';

export const USER_STATE_CHANGED = 'USER_STATE_CHANGED';

export const REGISTER_ATTEMPT = 'REGISTER_ATTEMPT';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const EDIT_USER_INFO_ATTEMPT = 'EDIT_USER_INFO_ATTEMPT';
export const EDIT_USER_INFO_SUCCESS = 'EDIT_USER_INFO_SUCCESS';
export const EDIT_USER_INFO_FAIL = 'EDIT_USER_INFO_FAIL';

export const CAST_VOTE_ATTEMPT = 'CAST_VOTE_ATTEMPT';
export const CAST_VOTE_SUCCESS = 'CAST_VOTE_SUCCESS';
export const CAST_VOTE_FAIL = 'CAST_VOTE_FAIL';

export const LOGOUT = 'LOGOUT';

export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
